platform :ios, '13.0'

target 'tkeybridgetest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tkeybridgetest
  pod 'Torus-directSDK', '~> 1.1.0'

end
